api_version = "2025-10"
uid = "7f8657b7-b730-3379-790f-e3e8b236b6e46838c67e"

[[extensions]]
type = "ui_extension"
name = "Order Downloads"
handle = "order-downloads"

[[extensions.targeting]]
module = "./src/index.jsx"
target = "customer-account.order-status.cart-line-list.render-after"

[[extensions.targeting]]
module = "./src/order-index.jsx"
target = "customer-account.order-index.block.render"
