# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fa9c876462a449fb62474d3f53a0979b"
name = "ctt-downloads"
application_url = "https://cttstore.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cttstore.com"

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[pos]
embedded = false
